#!/bin/bash
make -C ../
for file in $(find .. -name "*.s")
do
	echo $file
	filename="${file%.*}"
	../asm/asm $filename.s
	hexdump -C $filename.cor > my_cor
	../ressources/asm $filename.s
	hexdump -C $filename.cor > orig_cor
	diff my_cor orig_cor
	printf "\n"
done